### ISSUE TITLE
[Android] java.lang.NoSuchMethodError: No static method createRuntimeMessageAdapter

### ISSUE THREAD

**Issue by zacdemi** [square/react-native-square-reader-sdk#185]
### Describe the issue
  I just started getting this issue on Android when attempting to authorizeAsync(). The example project works, but following the sdk instructions leads to this error. Any help here would be appreciated. Thanks.

  Error log details:
  ```
      java.lang.NoSuchMethodError: No static method createRuntimeMessageAdapter(Ljava/lang/Class;)Lcom/squareup/wire/internal/RuntimeMessageAdapter; in class Lcom/squareup/wire/internal/ReflectionKt; or its super classes (declaration of 'com.squareup.wire.internal.ReflectionKt' appears in /data/app/~~HyqDwPgCiLpLh8WV_LFlwQ==/com.Brushfire.Brushfire.debug-mjqzsnXVvByAfUB2vdiKYA==/base.apk!classes27.dex)
        at com.squareup.wire.WireTypeAdapterFactory.create(WireTypeAdapterFactory.kt:77)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at retrofit2.converter.gson.GsonConverterFactory.requestBodyConverter(GsonConverterFactory.java:71)
        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:304)
        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:284)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:732)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:306)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:193)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:192)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy6.login(Unknown Source)
        at com.squareup.sdk.reader.authorization.ReaderSdkAuthenticator.login(ReaderSdkAuthenticator.kt:116)
        at com.squareup.sdk.reader.authorization.RealAuthorizationManager.authorize(RealAuthorizationManager.java:109)
        at com.squareup.sdk.reader.react.AuthorizationModule$2.run(AuthorizationModule.java:117)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
  ```

### Expected behavior

**Environment (please complete the following information):**

  - platform: Android
  - OS and version: 11
  - dev environment: MacOS
  - Reader SDK version: [e.g. 1.4.0]

  In addition: Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 11.6.3
    CPU: (8) arm64 Apple M1
    Memory: 108.42 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.67.2 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by CharmisG** [comment]
@zacdemi 
Sorry for the delay !!
Can you please pull latest code it's resolved !!
