### ISSUE TITLE
Αndroid Q (10) crash

### ISSUE THREAD

**Issue by SudoPlz** [square/react-native-square-reader-sdk#82]
### Describe the issue

When I try to launch the app on Android Q (10) the app instantly crashes.

  Error log details:
  ```
  2019-09-07 04:46:52.364 1931-1931/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.app.android, PID: 1931
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
        at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
        at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at com.squareup.receiving.ReceivedResponse$Companion$receiveFromRetrofit$2$2.apply(ReceivedResponse.kt:167)
        at com.squareup.receiving.ReceivedResponse$Companion$receiveFromRetrofit$2$2.apply(ReceivedResponse.kt:105)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69) 
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at java.lang.reflect.Field.getInt(Native Method)
        at com.squareup.util.Telephony.<init>(Telephony.java:30)
        at com.squareup.util.Telephony_Factory.get(Telephony_Factory.java:21)
        at com.squareup.util.Telephony_Factory.get(Telephony_Factory.java:8)
        at com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get(AndroidModule_ProvideNetworkTypeFactory.java:21)
        at com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get(AndroidModule_ProvideNetworkTypeFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.squareup.server.RegisterHttpInterceptor.intercept(RegisterHttpInterceptor.java:42)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.squareup.server.UrlRedirectInterceptor.intercept(UrlRedirectInterceptor.java:40)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-09-07 04:46:52.364 1931-1931/? E/AndroidRuntime:     at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.squareup.server.ProfilingInterceptor.intercept(ProfilingInterceptor.java:24)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.squareup.http.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:32)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at shadow.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at shadow.okhttp3.RealCall.execute(RealCall.java:92)
        at shadow.retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at shadow.retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at shadow.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-09-07 04:46:52.435 1282-1871/? E/InputDispatcher: channel '91ada36 com.myapp.app.android/com.myapp.app.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-09-07 04:47:00.584 2087-2087/? E/roid.apps.turb: Not starting debugger since process cannot load the jdwp agent.

  ```

### To Reproduce

  - Run any app that contains the SDK on Android Q (10) (API 29)

### Expected behavior

**Environment (please complete the following information):**

  - platform: Android 10 device
  - Reader SDK version: https://github.com/square/react-native-square-reader-sdk/commit/98e75a0c3ca899f2f3aad7ee805597f65dec5fe5

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 20.69 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by SudoPlz** [comment]
Fixed by updating to 1.3.2
